version: '3'

services:

  contact-postgres:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=contact_dev
      - POSTGRES_USER=contact_dev 
      - POSTGRES_PASSWORD=contact_dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db
  
volumes:
  postgres-data: